language: ruby
rvm:
  - 2.3.8
  - 2.4.7
  - 2.5.6
  - 2.6.4
before_install:
  - gem install origen
script:
  - bundle exec origen -v
  - bundle exec origen t dut.rb
  - bundle exec origen e j750.rb
  - bundle exec origen test -c
  - bundle exec origen web compile --no-serve
  - bundle exec origen lint --no-correct
env:
  - ORIGEN_GEM_USE_FROM_SYSTEM=false ORIGEN_GEM_MANAGE_BUNDLER=false
